# This workflow will deploy the LZA
name: LZA Deployment

on:
  # When a pull request is issued for the main branch
  pull_request:
    branches: [ "main" ]
    paths:
      - scenarios/aca-internal/bicep
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
#Set any environment variables needed
env:
  ENVIRONMENT: dev
  LOCATION: northeurope

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # The lint job performs linting on the bicep code
  lint:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs the Bicep linter to ensure build is successful
      - name: Run Bicep linter
        run: az bicep build --file ./scenarios/aca-internal/bicep/main.bicep

  validate:
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - uses: actions/checkout@v3
      - uses: azure/login@v1
        name: Sign in to Azure
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - uses: azure/arm-deploy@v1.0.9
        name: Run preflight validation
        with:
          deploymentName: ${{ github.run_number }}
          scope: subscription
          region: ${{ env.LOCATION }}
          template: ./scenarios/aca-internal/bicep/main.bicep
          parameters: ./scenarios/aca-internal/bicep/main.parameters.jsonc
          deploymentMode: Validate

  preview:
    runs-on: ubuntu-latest
    needs: [lint, validate]
    steps:
      - uses: actions/checkout@v3
      - uses: azure/login@v1
        name: Sign in to Azure
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - uses: Azure/cli@v1
        name: Run what-if
        with:
          azcliversion: 2.45.0
          inlineScript: |
            az deployment sub what-if \
              --location ${{ ${{ env.LOCATION }} }} \
              --template-file ./scenarios/aca-internal/bicep/main.bicep \
              --parameters ./scenarios/aca-internal/bicep/main.parameters.jsonc \
              --parameters deployHelloWorldSample=false

  deploy:
    runs-on: ubuntu-latest
    needs: [preview]
    steps:
      - uses: actions/checkout@v3
      - uses: azure/login@v1
        name: Sign in to Azure
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - uses: azure/arm-deploy@v1.0.9
        name: Deployment
        with:
          deploymentName: "GitHubAction-${{ github.run_number }}"
          scope: subscription
          region: ${{ ${{ env.LOCATION }} }}
          template: ./scenarios/aca-internal/bicep/main.bicep
          parameters: ./scenarios/aca-internal/bicep/main.parameters.jsonc parameters deployHelloWorldSample=false
          failOnStdErr: false
